'use strict';
(function(){
const node=id=>document.getElementById(id),key='huwster-temple-profile-v1';let catalogue=null,prefs=null,plan=null,url=null;
function clone(value){return JSON.parse(JSON.stringify(value));}
function saveFile(content,name,type){const link=document.createElement('a'),blob=URL.createObjectURL(new Blob([content],{type}));link.href=blob;link.download=name;link.click();setTimeout(()=>URL.revokeObjectURL(blob),1000);}
function status(text){node('temple-status').textContent=text;}
function fields(){return {...clone(prefs),primary_temple:node('temple-primary').value,palette:node('temple-palette').value,density:node('temple-density').value,hud_layout:node('temple-layout').value,text_scale:Number(node('temple-scale').value),interior_style:node('temple-interior').value,interior_detail:node('temple-detail').value,brand_preferences:node('temple-brands').value.split(',').map(s=>s.trim()).filter(Boolean),profile_name:node('temple-profile').value,profile_state:node('temple-profile').value.trim()?'local-profile':'anonymous',visible_panels:Array.from(node('temple-panels').querySelectorAll('input:checked')).map(input=>input.value)};}
function fill(){for(const [id,name] of [['temple-primary','primary_temple'],['temple-palette','palette'],['temple-density','density'],['temple-layout','hud_layout'],['temple-scale','text_scale'],['temple-interior','interior_style'],['temple-detail','interior_detail'],['temple-profile','profile_name']])node(id).value=prefs[name];node('temple-brands').value=prefs.brand_preferences.join(', ');for(const input of node('temple-panels').querySelectorAll('input'))input.checked=prefs.visible_panels.includes(input.value);}
function render(){document.body.dataset.templePalette=prefs.palette;document.body.dataset.templeInterior=prefs.interior_style;document.body.dataset.hudDensity=prefs.density;document.body.dataset.hudLayout=prefs.hud_layout;document.documentElement.style.setProperty('--hud-scale',prefs.text_scale/100);for(const panel of document.querySelectorAll('[data-hud-panel]'))panel.hidden=!prefs.visible_panels.includes(panel.dataset.hudPanel);if(url)URL.revokeObjectURL(url);url=URL.createObjectURL(new Blob([plan.svg],{type:'image/svg+xml'}));node('temple-plan').src=url;node('temple-summary').replaceChildren();for(const [panel,text] of [['ranks','Seven declared temple priorities with customizable preference; role ranks remain available in the world workbench.'],['lore',prefs.persona+' is a fictional persona, not a user identity or verified species.'],['paperwork','Interior review: maximum documented counter-review. '+prefs.settings_terms.join(' · ')]]){const card=document.createElement('article');card.dataset.hudPanel=panel;card.hidden=!prefs.visible_panels.includes(panel);const title=document.createElement('h3');title.textContent=panel;const p=document.createElement('p');p.textContent=text;card.append(title,p);node('temple-summary').append(card);}status((prefs.profile_state==='local-profile'?'Local profile: '+prefs.profile_name:'Anonymous standard defaults')+' · '+prefs.primary_temple+' first · '+prefs.interior_style+' artificial botanicals');window.dispatchEvent(new Event('huwster-settings-changed'));}
async function session(){for(let i=0;i<50;i++){if(token)return;await new Promise(resolve=>setTimeout(resolve,100));}throw Error('Local session is not ready; standard defaults remain available.');}
async function apply(save){try{await session();const candidate=fields();if(save&&!candidate.profile_name.trim())throw Error('Supply a local profile name before saving.');const result=await action('temple-blueprint',{settings:candidate});if(!result)throw Error('Settings were rejected; correct the supplied values.');prefs=result.settings;plan=result;fill();render();if(save){try{localStorage.setItem(key,JSON.stringify(prefs));status('Local profile saved on this browser: '+prefs.profile_name);}catch(error){status('Settings applied for this session, but local profile storage is unavailable.');}}}catch(error){status(error.message);}}
node('temple-apply').addEventListener('click',()=>apply(false));node('temple-save').addEventListener('click',()=>apply(true));
node('temple-reset').addEventListener('click',async()=>{try{localStorage.removeItem(key);}catch(error){}prefs=clone(catalogue.defaults);plan=await fetch('/api/temple-blueprint').then(r=>r.json());fill();render();status('Anonymous launch defaults restored; the local saved profile was removed.');});
node('temple-export').addEventListener('click',()=>{if(plan)saveFile(plan.svg,'huwster-temple-blueprint.svg','image/svg+xml');});node('temple-settings-export').addEventListener('click',()=>{if(prefs)saveFile(JSON.stringify(prefs,null,2),'huwster-launch-settings.json','application/json');});
globalThis.HuwsterTempleHUD={current:()=>prefs?clone(prefs):null};
Promise.all([fetch('/api/temple').then(r=>r.json()),fetch('/api/temple-blueprint').then(r=>r.json())]).then(async results=>{catalogue=results[0];plan=results[1];prefs=clone(catalogue.defaults);for(const entry of catalogue.temples){const option=document.createElement('option');option.value=entry.id;option.textContent=entry.priority+'. '+entry.name;node('temple-primary').append(option);}for(const entry of catalogue.palettes){const option=document.createElement('option');option.value=entry;option.textContent=entry;node('temple-palette').append(option);}for(const entry of catalogue.interior_styles){const option=document.createElement('option');option.value=entry;option.textContent=entry.replaceAll('-',' ');node('temple-interior').append(option);}for(const panel of catalogue.panels){const label=document.createElement('label'),input=document.createElement('input');input.type='checkbox';input.value=panel;input.checked=true;input.disabled=panel==='settings';label.append(input,document.createTextNode(' '+panel));node('temple-panels').append(label);}fill();render();let saved=null;try{saved=JSON.parse(localStorage.getItem(key));}catch(error){status('Saved profile unreadable; anonymous defaults applied.');}if(saved){try{await session();const result=await action('temple-blueprint',{settings:saved});if(result){prefs=result.settings;plan=result;fill();render();}else status('Saved profile invalid; anonymous defaults applied.');}catch(error){status(error.message);}}}).catch(error=>status('Temple layout unavailable: '+error.message));
})();
