const assert=require('node:assert/strict');const fs=require('node:fs');const vm=require('node:vm');
const core=require('../../extensions/instagram-orange/core.js');
assert.equal(core.mediaURL('https://evilcdninstagram.com/a'),null);assert.equal(core.mediaURL('http://s.cdninstagram.com/a'),null);assert.equal(core.mediaURL('https://user:pass@s.cdninstagram.com/a'),null);assert.equal(core.mediaURL('blob:https://www.instagram.com/1'),null);assert.ok(core.mediaURL('https://s.cdninstagram.com/a?x=1'));assert.equal(core.instagram('https://instagram.com.evil/a'),false);
assert.equal(core.unique([{url:'https://s.cdninstagram.com/a'},{url:'https://s.cdninstagram.com/a'}]).length,1);assert.equal(core.unique(Array.from({length:210},(_,i)=>({url:`https://s.cdninstagram.com/${i}`}))).length,200);
let listener,changes;let downloads=[];let cancelled=[];
const chrome={runtime:{id:'test',getURL:path=>'chrome-extension://test/'+path,onMessage:{addListener:fn=>listener=fn}},tabs:{get:async id=>({id,url:'https://www.instagram.com/test/'}),onRemoved:{addListener(){}}},downloads:{download:async options=>{downloads.push(options);return downloads.length;},cancel:async id=>cancelled.push(id),onChanged:{addListener:fn=>changes=fn}}};
vm.runInNewContext(fs.readFileSync('extensions/instagram-orange/worker.js','utf8'),{chrome,OrangeCore:core,importScripts(){},setTimeout:fn=>{fn();}});
const request=(message,sender)=>new Promise(resolve=>listener(message,sender,resolve));
(async()=>{const page={id:'test',tab:{id:1,url:'https://www.instagram.com/test/'}},popup={id:'test',url:'chrome-extension://test/popup.html'};
assert.match((await request({type:'download',items:[]},page)).error,/confirm/);
assert.match((await request({type:'grant',tabId:1,allowed:true},page)).error,/authorized/);
await request({type:'grant',tabId:1,allowed:true},popup);
assert.match((await request({type:'download',items:[{url:'https://evil.com/a'}]},page)).error,/No supported/);
assert.equal((await request({type:'download',items:[{url:'https://s.cdninstagram.com/a',kind:'video'}]},page)).total,1);
await new Promise(r=>setImmediate(r));assert.equal(downloads[0].filename,'RasnikiInstagram/media-001.mp4');
changes({id:1,state:{current:'complete'}});assert.equal((await request({type:'status'},popup)).complete,1);
await request({type:'download',items:[{url:'https://s.cdninstagram.com/b'}]},page);await new Promise(r=>setImmediate(r));await request({type:'cancel'},popup);assert.deepEqual(cancelled,[2]);
await request({type:'grant',tabId:1,allowed:false},popup);assert.match((await request({type:'download',items:[]},page)).error,/confirm/);
console.log('Instagram URL, deduplication, cap, permission, download, completion and cancellation checks passed.');
})().catch(e=>{console.error(e);process.exitCode=1;});
